In [1]:
%matplotlib inline

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

#### 【練習 A】找到給定範圍的質數

我們知道, 對任意的 $n$, 一定有個質數 $p$, 符合

$$n < p \leq n!+1$$

讓使用者輸入一個 $n$, 用 Python 把符合條件的 $p$ 找出來。

我們這裡只是試著手動做一個範例, 看怎麼用 Python 幫我們做這樣的事情。

In [2]:
n = 9487

In [3]:
sp.nextprime(n)

9491

#### 【練習 B】 找差距很大的相鄰質數

我們知道, 對任意的 $N$, 存在兩個連續質數 $p_n, p_{n+1}$, 使得

$$|p_{n+1} - p_n| > N$$

寫一個 Python 程式, 輸入 $N$, 可以找到兩個質數 $p_n, p_{n+1}$ 符合所求。


這裡一樣我們試用簡單的例子, 去感受一下 Python 該怎麼做。

In [4]:
N = 7

k = 7*6*5*4*3*2*1 + 2

這裡求 $N!$ 的方式有點遜! 其實 `sympy` 當然可以幫助我們, 不過查一下怎麼做就交給大家了。

In [5]:
k

5042

In [6]:
sp.nextprime(k)

5051

這裡我們找到了 $p_{n+1}$, 要找到 $p_n$ 怎麼做呢? 大家可以試試看。

#### 【練習 C】 求所有小於等於 $n$ 的質數

用埃拉托色尼 (Eratosthenes) 的方法, 找出 $2$ 到 $n$ 的所有質數。

我們這裡最重要的, 是有個質數 $p$, 我們想判斷對另一個整數 $k$, 會不會有 $p|k$。

In [7]:
9%2

1

In [8]:
18%4

2

我們發現, 原來

    m%n

是 $m$ 除以 $n$ 的餘數。

In [9]:
18%3

0

這樣我們就知道 $3 | 18$。

接著我們試著用 Eratosthenes 篩檢法找質數。

In [11]:
n = 20

egg = list(range(2, 21))

In [12]:
egg

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

現在 `egg` 中就是我們所有候選人, 我們要由 $2$ 開始看是不是某個數的因數, 是的話就把那個數刪去。

一種做法是這樣。

In [13]:
egg = [k for k in egg if k%2 != 0]

In [14]:
egg

[3, 5, 7, 9, 11, 13, 15, 17, 19]

真的刪掉 $2$ 的倍數了! 但不幸的是 $2$ 也被刪掉, 所以你需要思考怎麼樣把 $2$ 留下來。其中一個方式是, 我們確認是質數的先用另一個 list 記下來。

我們再繼續。

In [15]:
egg = [k for k in egg if k%3 !=0]

In [16]:
egg

[5, 7, 11, 13, 17, 19]

我們再次發現, 要在 list 的 $3$ 又被刪掉了!

試把完整程式寫出來!

### 不用迴圈的篩法!

剛剛我們用的是之前介紹過 Python "list comprehension" 的做法, 缺點是基本上這是 `for` 迴圈。而 `for` 迴圈在數據分析中有如罪惡般的存在, 原因是它不能平行化。

我們來個可以平行運算的 `numpy array`。

In [17]:
egg = np.arange(2, 21)

In [18]:
egg

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

我們想選不會被 $2$ 整除的那些數字, 先用工人智慧試試看。

In [19]:
ham = np.array([False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False])

In [20]:
len(egg)

19

In [21]:
len(ham)

19

這有什麼用呢? 魔術要來了...

In [22]:
egg[ham]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

真的成功了! 但這種方式也太呆了!! Python 難道不會自己做嗎?

In [23]:
spam = egg % 2 != 0

我們看看 `spam` 的內容。

In [25]:
spam

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

自動生出判斷的 `array` 了耶。於是這些數字就可以快速選出來。

In [34]:
egg[spam]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])