In [1]:
%matplotlib inline

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

#### 【重點】

如果你發現在用 `sympy` 時數學式子沒有像這裡漂亮, 請先下達

    sp.init_printing()

這個指令來美化你的輸出。

### 1. 用 list 表示向量和矩陣

#### (a) 向量篇

In [2]:
u = [3, 5, 6]

要換成 `numpy` 的 array 自然是這樣。

In [7]:
u = np.array([3, 5, 6])

`np.array` 的好處是我們真的可以做一般向量的加法、純量乘法!

In [8]:
v = np.array([1, 0 , 2])

向量加法。

In [9]:
u + v

array([4, 5, 8])

純量乘法。

In [10]:
1.7*u

array([ 5.1,  8.5, 10.2])

#### (b) 矩陣

我們數字可分為:

1. 純量: 1, 3, 4 (0 階 tensor)
2. 向量: [1, 3, 4] 注意是純量所成的 list (1 階 tensor)
3. 矩陣: 自然是向量所成的 list (2 階 tensor)

比如說:

$$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}$$

一列看成一個 list, 有兩列, 所以應該要看成這樣。

In [4]:
A = [[1,2,3], [4,5,6]]

但是這樣子之後沒辦法做矩陣的運算! 所以一樣變成 `np.array`。

In [5]:
A = np.array(A)

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6]])

我們常常會看 A 矩陣的 shape。

In [12]:
A.shape

(2, 3)

果然是一個 $2 \times 3$ 的矩陣沒有錯! (嚴格說是 order 2 的陣列)

In [14]:
B = np.array([[1, 2], [2, 1], [1, 1]])

In [15]:
B.shape

(3, 2)

看來 A, B 矩陣可以相乘! 我們矩陣的乘法是 `@` (事實上是內積)。

In [16]:
C = A@B

In [18]:
C

array([[ 8,  7],
       [20, 19]])

一個矩陣乘以一個向量呢? 例如我們想計算:

$$A \mathbf{x},$$

其中 $\mathbf{x} = \begin{bmatrix}1 \\ 0 \\ 2\end{bmatrix}$。

嚴格說來, $\mathbf{x}$ 是一個 $3 \times 1$ 的矩陣, 所以我們應該這麼算。

In [19]:
x = np.array([[1], [0], [2]])

In [20]:
A@x

array([[ 7],
       [16]])

但是矩陣乘向量真的太常用了! 所以你可能會好奇, 要是直接定義一個 [1, 0, 2] 的向量會如何?

In [21]:
v = np.array([1, 0, 2])

In [22]:
A@v

array([ 7, 16])

成功了! 雖然其實 shape 是不一樣的, 不過這也讓我們知道實務上這樣算應該很好用。所以, `numpy` 真的可以幫我們做矩陣運算。

不過我們會發現, 好像要算 inverse 啦, determinant 等等不是那麼方便。畢竟這不是「真的」矩陣。雖然 `numpy` 也有「真的」矩陣的作法, 不過一般實務上我們用 array 的型式就可以了。進階計算我們換給 `sympy` 算。

### 2. `sympy` 就像我們一般算數學一樣!

`sympy` 是